//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.19 at 01:50:00 PM CEST 
//


package mycellar;

import java.util.Calendar;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Titre : Cave à vin</p>
 * <p>Description : Votre description</p>
 * <p>Copyright : Copyright (c) 1998</p>
 * <p>Société : Seb Informatique</p>
 * @author Sébastien Duché
 * @version 0.6
 * @since 25/10/17
 */

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element ref="{}Bouteille"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "date",
    "type",
    "bouteille",
    "time"
})
@XmlRootElement(name = "History")
public class History {

    @XmlElement(required = true)
    protected String date;
    protected int type;
    protected Date time;
    @XmlElement(name = "Bouteille", required = true)
    protected Bouteille bouteille;
	
	public final static int ADD = 0;
    public final static int MODIFY = 1;
    public final static int DEL = 2;
	
	/**
   * History: Contructeur avec une bouteille et un type d'action
   *
   * @param _oBottle Bouteille
   * @param _nType int
   */
  public History(Bouteille bouteille, int type) {
    this.bouteille = bouteille;
    this.type = type;
    Calendar oCal = Calendar.getInstance();
    this.time = oCal.getTime();
    date = "";
    if (oCal.get(Calendar.DATE) < 10) {
      date = "0";
    }
    date += oCal.get(Calendar.DATE);
    date += "/";
    if (oCal.get(Calendar.MONTH) < 9) {
      date += "0";
    }
    date += (oCal.get(Calendar.MONTH) + 1);
    date += "/";
    date += oCal.get(Calendar.YEAR);
  }

    public History() {}

	/**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }    

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the type property.
     * 
     */
    public int getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     */
    public void setType(int value) {
        this.type = value;
    }
    
    public boolean isDeleted() {
    	return this.type == DEL;
    }

    public Date getTime() {
		return time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	/**
     * Gets the value of the bouteille property.
     * 
     * @return
     *     possible object is
     *     {@link Bouteille }
     *     
     */
    public Bouteille getBouteille() {
        return bouteille;
    }

    /**
     * Sets the value of the bouteille property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bouteille }
     *     
     */
    public void setBouteille(Bouteille value) {
        this.bouteille = value;
    }

}
