//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.19 at 01:50:00 PM CEST 
//


package mycellar;

import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.transform.stream.StreamResult;

/**
 * <p>Titre : Cave à vin</p>
 * <p>Description : Votre description</p>
 * <p>Copyright : Copyright (c) 1998</p>
 * <p>Société : Seb Informatique</p>
 * @author Sébastien Duché
 * @version 0.3
 * @since 24/10/17
 */

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}History" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "history"
})
@XmlRootElement(name = "HistoryList")
public class HistoryList {

    @XmlElement(name = "History", required = true)
    protected List<History> history;

    /**
     * Gets the value of the history property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the history property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHistory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link History }
     * 
     * 
     */
    public List<History> getHistory() {
        if (history == null) {
            history = new ArrayList<History>();
        }
        return this.history;
    }

    public void addLast(History history) {
    	getHistory().add(history);
    }
    
    public void remove(History history) {
    	getHistory().remove(history);
    }
    
    public void clear() {
    	getHistory().clear();
    }
    
    public static boolean loadXML() {
		Debug("Loading JAXB File");
		File f = new File(Program.getXMLBottlesFileName());
		if(!f.exists())
			return false;
		try {
            JAXBContext jc = JAXBContext.newInstance(HistoryFactory.class);
            Unmarshaller u = jc.createUnmarshaller();
            HistoryList lb = 
                (HistoryList)u.unmarshal(new FileInputStream(f));
            Program.getStorage().setHistoryList(lb);
        } catch( Exception e ) {
            Program.showException(e);
            return false;
        }
		Debug("Loading JAXB File Done");
		return true;
	}
    
    public static boolean loadXML(File f) {
		Debug("Loading JAXB File "+f.getAbsolutePath());
		if(!f.exists())
			return false;
		try {
            JAXBContext jc = JAXBContext.newInstance(HistoryFactory.class);
            Unmarshaller u = jc.createUnmarshaller();
            HistoryList lb = 
                (HistoryList)u.unmarshal(new FileInputStream(f));
            Program.getStorage().setHistoryList(lb);
        } catch( Exception e ) {
            Program.showException(e);
            return false;
        }
		Debug("Loading JAXB File Done");
		return true;
	}
	
	public static boolean writeXML() {
		return writeXML(Program.getHistoryList(), new File(Program.getXMLBottlesFileName()));
	}
	
	public static boolean writeXML(File f) {
		return writeXML(Program.getHistoryList(), f);
	}
	
	public static boolean writeXML(HistoryList liste, File f) {
		Debug("Writing JAXB File");
		try {
            JAXBContext jc = JAXBContext.newInstance(HistoryFactory.class);
            Marshaller m = jc.createMarshaller();
            m.setProperty( Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
            m.marshal(liste, new StreamResult(f));
        } catch( Exception e ) {
        	Program.showException(e);
        	return false;
        }
		Debug("Writing JAXB File Done");
		return true;
	}

	/**
	 * Debug
	 *
	 * @param sText String
	 */
	public static void Debug(String sText) {
		Program.Debug("HistoryList: " + sText );
	}
}
