//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.14 at 12:30:49 PM CEST 
//


package mycellar;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import mycellar.countries.Countries;
import mycellar.countries.Country;
import mycellar.vignobles.Appelation;

/**
 * <p>Titre : Cave à vin</p>
 * <p>Description : Votre description</p>
 * <p>Copyright : Copyright (c) 2014</p>
 * <p>Société : Seb Informatique</p>
 * @author Sébastien Duché
 * @version 0.6
 * @since 21/01/17
 */

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AOC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IGP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AOP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
	"country",
    "name",
    "aoc",
    "igp",
    "aop"
})
@XmlRootElement(name = "vignoble")
public class Vignoble implements Serializable {

	private static final long serialVersionUID = -4668411717652334826L;
	
	@XmlElement(required = true)
    public String country;
    @XmlElement(required = false)
    public String name;
    @XmlElement(name = "AOC", required = false)
    public String aoc;
    @XmlElement(name = "IGP", required = false)
    public String igp;
    @XmlElement(name = "AOP", required = false)
    public String aop;
    
    public Vignoble() {
	}
    
    public Vignoble(String country) {
		this.country = country;
	}

    public Vignoble(String country, String name) {
    	this.country = country;
		this.name = name;
	}

	public Vignoble(String country, String name, String aoc) {
		this.country = country;
		this.name = name;
		this.aoc = aoc;
	}

	public Vignoble(String country, String name, String aoc, String igp) {
		this.country = country;
		this.name = name;
		this.aoc = aoc;
		this.igp = igp;
	}

	public Vignoble(String country, String name, String aoc, String igp, String aop) {
		this.country = country;
		this.name = name;
		this.aoc = aoc;
		this.igp = igp;
		this.aop = aop;
	}

	/**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }
    
	/**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the aoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAOC() {
        return aoc;
    }

    /**
     * Sets the value of the aoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAOC(String value) {
        this.aoc = value;
    }

    /**
     * Gets the value of the igp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIGP() {
        return igp;
    }

    /**
     * Sets the value of the igp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIGP(String value) {
        this.igp = value;
    }

    /**
     * Gets the value of the aop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAOP() {
        return aop;
    }

    /**
     * Sets the value of the aop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAOP(String value) {
        this.aop = value;
    }
    
    public boolean isAppellationEmpty() {
    	return (aoc == null || aoc.isEmpty())
    			&& (aop == null || aop.isEmpty())
    			&& (igp == null || igp.isEmpty());
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((aoc == null) ? 0 : aoc.hashCode());
		result = prime * result + ((aop == null) ? 0 : aop.hashCode());
		result = prime * result + ((country == null) ? 0 : country.hashCode());
		result = prime * result + ((igp == null) ? 0 : igp.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Vignoble other = (Vignoble) obj;
		if (aoc == null) {
			if (other.aoc != null)
				return false;
		} else if (!aoc.equals(other.aoc))
			return false;
		if (aop == null) {
			if (other.aop != null)
				return false;
		} else if (!aop.equals(other.aop))
			return false;
		if (country == null) {
			if (other.country != null)
				return false;
		} else if (!country.equals(other.country))
			return false;
		if (igp == null) {
			if (other.igp != null)
				return false;
		} else if (!igp.equals(other.igp))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		if(country != null) {
			Country c = Countries.findByIdOrLabel(country);
			if(c != null)
				sb.append(c.getId());
			else
				sb.append(country);
		}
		sb.append("-");
		sb.append(name);
		sb.append("-");
		if(aoc != null)
			sb.append(aoc);
		sb.append("-");
		if(aop != null)
			sb.append(aop);
		/*else
			sb.append(aoc);*/
		sb.append("-");
		if(igp != null)
			sb.append(igp);
		return sb.toString();
	}

	public void setValues(Appelation ap) {
		aoc = ap.getAOC();
		aop = ap.getAOP();
		igp = ap.getIGP();
	}
}
