//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.18 at 06:16:55 PM CET 
//


package Cave;

import java.io.File;
import java.io.FileInputStream;
import java.util.LinkedList;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.transform.stream.StreamResult;

/**
 * <p>Titre : Cave à vin</p>
 * <p>Description : Votre description</p>
 * <p>Copyright : Copyright (c) 2012</p>
 * <p>Société : Seb Informatique</p>
 * @author Sébastien Duché
 * @version 0.5
 * @since 20/05/15
 */


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Bouteille" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bouteille"
})
@XmlRootElement(name = "ListeBouteille")
@XmlSeeAlso(Bouteille.class)
public class ListeBouteille {

    @XmlElement(name = "Bouteille", required = true)
    protected LinkedList<Bouteille> bouteille;

    /**
     * Gets the value of the bouteille property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bouteille property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBouteille().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bouteille }
     * 
     * 
     */
    public LinkedList<Bouteille> getBouteille() {
        if (bouteille == null) {
            bouteille = new LinkedList<Bouteille>();
        }
        return this.bouteille;
    }
    
    public void resetBouteille() {
        bouteille = null;
    }
    
    public static boolean loadXML() {
		Debug("Loading JAXB File");
		File f = new File(Program.getXMLBottlesFileName());
		if(!f.exists())
			return false;
		try {
            JAXBContext jc = JAXBContext.newInstance(ObjectFactory.class);
            Unmarshaller u = jc.createUnmarshaller();
            ListeBouteille lb = 
                (ListeBouteille)u.unmarshal(new FileInputStream(f));
            Program.getStorage().setListBouteilles(lb);
        } catch( Exception e ) {
            Program.showException(e);
            return false;
        }
		Debug("Loading JAXB File Done");
		return true;
	}
    
    public static boolean loadXML(File f) {
		Debug("Loading JAXB File "+f.getAbsolutePath());
		if(!f.exists())
			return false;
		try {
            JAXBContext jc = JAXBContext.newInstance(ObjectFactory.class);
            Unmarshaller u = jc.createUnmarshaller();
            ListeBouteille lb = 
                (ListeBouteille)u.unmarshal(new FileInputStream(f));
            Program.getStorage().addBouteilles(lb);
        } catch( Exception e ) {
            Program.showException(e);
            return false;
        }
		Debug("Loading JAXB File Done");
		return true;
	}
	
	public static boolean writeXML() {
		return writeXML(Program.getStorage().getListBouteilles(), new File(Program.getXMLBottlesFileName()));
	}
	
	public static boolean writeXML(File f) {
		return writeXML(Program.getStorage().getListBouteilles(), f);
	}
	
	public static boolean writeXML(ListeBouteille liste, File f) {
		Debug("Writing JAXB File");
		try {
            JAXBContext jc = JAXBContext.newInstance(ObjectFactory.class);
            Marshaller m = jc.createMarshaller();
            m.setProperty( Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
            m.marshal(liste, new StreamResult(f));
        } catch( Exception e ) {
        	Program.showException(e);
        	return false;
        }
		Debug("Writing JAXB File Done");
		return true;
	}

	/**
	 * Debug
	 *
	 * @param sText String
	 */
	public static void Debug(String sText) {
		Program.Debug("ListeBouteille: " + sText );
	}
}
